name: Deploy to Staging

on:
  push:
    branches:
      - feature/staging-environment

env:
  SKIP_TESTS: true  # GitHub Actions environment variable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -Pstaging

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: transfer-scheduler
          path: target/transfer-scheduler.jar

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !env.SKIP_TESTS }}  # Skip if SKIP_TESTS is true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run unit tests
        run: mvn test

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    if: ${{ !env.SKIP_TESTS }}  # Skip if SKIP_TESTS is true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run integration tests
        run: mvn verify -Pintegration-test

  deploy-staging:
    runs-on: ubuntu-latest
    needs:
      - build
      - unit-tests
      - integration-tests
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: transfer-scheduler
          path: target

      - name: Build Docker image
        run: docker build -t transfer-scheduler:staging .

      - name: Deploy to staging
        run: docker-compose up -d