
name: Deploy to Staging

on:
  push:
    branches:
      - feature/staging-environment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -Pstaging

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: transfer-scheduler
          path: target/transfer-scheduler.jar